openapi: 3.0.0
info:
  title: Title
  description: description
  version: 1.0.0
servers:
  - url: http://127.0.0.1:8000
paths:
  /api/user:
    get:
      operationId: getUser
      summary: get user profile
      description: fetches logged in user data
      responses:
        "200":
          description: Successful response

  /api/speakers:
    get:
      operationId: getSpeakers
      summary: get speakers list
      description: fetches all speakers list for all conferences
      responses:
        "200":
          description: Successful response
